### ISSUE TITLE
Iteration 1 Feedback

### ISSUE THREAD

**Issue by kaesrel** [inwpolol/ku-polls#24]
* polls/admin.py does not register choice, so no choice can be added for the questions.
* In requirements.txt, unnecessary built-in modules ("datetime", "os", "sys").
* No docstring in polls/models.py

**Comment by inwpolol** [comment]
"polls/admin.py does not register choice, so no choice can be added for the questions." is this in Django tutorial 7?
Isn't that out of range of iteration1 instruction?
